import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import productsRouter from "./products";
import salesRouter from "./sales";
import customersRouter from "./customers";
import shortagesRouter from "./shortages";
import salariesRouter from "./salaries";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import shiftsRouter from "./shifts";
import tasksRouter from "./tasks";
import expensesRouter from "./expenses";
import advancesRouter from "./advances";
import onlineOrdersRouter from "./online-orders";
import distributorOffersRouter from "./distributor-offers";
import auditRouter from "./audit";
import backupRouter from "./backup";
import loyaltyRouter from "./loyalty";
import returnsRouter from "./returns";
import analyticsRouter from "./analytics";
import priceSuggestionsRouter from "./price-suggestions";
import stockoutPredictionRouter from "./stockout-prediction";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(productsRouter);
router.use(salesRouter);
router.use(customersRouter);
router.use(shortagesRouter);
router.use(salariesRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(shiftsRouter);
router.use(tasksRouter);
router.use(expensesRouter);
router.use(advancesRouter);
router.use(onlineOrdersRouter);
router.use(distributorOffersRouter);
router.use(auditRouter);
router.use(backupRouter);
router.use(loyaltyRouter);
router.use(returnsRouter);
router.use(analyticsRouter);
router.use(priceSuggestionsRouter);
router.use(stockoutPredictionRouter);

export default router;
